SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Users;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE Users (
    UserID INT PRIMARY KEY,
    Username VARCHAR(50) UNIQUE,
    Email VARCHAR(100) UNIQUE
);
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BlogPosts;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE BlogPosts (
    PostID INT PRIMARY KEY,
    UserID INT,
    TITLE VARCHAR(256),
    CONTENT TEXT,
    Timestamp TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Comments;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE Comments (
    CommentID INT PRIMARY KEY,
    PostID INT,
    CommentName VARCHAR(50),
    CommentText TEXT,
    Timestamp TIMESTAMP,
    FOREIGN KEY (PostID) REFERENCES BlogPosts(PostID)  
);